//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.201.20.0
//     UI Plugin:   1.3801.23.0
//
//     Project:     MSSXpanel
//     Version:     1.0.0.0
//     Sdk:         CH5:2.12.0
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using MSSXpanel;

namespace MSSXpanel
{

    /// <summary>
    /// HeaderBar
    /// </summary>
    public partial interface IHeaderBar 
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event PowerButton.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> PowerButton_PressEvent;

        /// <summary>
        /// PowerButton.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void PowerButton_Selected(HeaderBarBoolInputSigDelegate callback);

        /// <summary>
        /// PowerButton.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void PowerButton_Selected(bool digital);

        /// <summary>
        /// RoomNameLabel.Indirect Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void RoomNameLabel_Indirect(HeaderBarStringInputSigDelegate callback);

        /// <summary>
        /// RoomNameLabel.Indirect Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void RoomNameLabel_Indirect(string serial);
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="headerbar">The <see cref="IHeaderBar"/> on which to apply the feedback.</param>
    public delegate void HeaderBarBoolInputSigDelegate(BoolInputSig boolInputSig, IHeaderBar headerbar);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="stringInputSig">The <see cref="StringInputSig"/> joinInfo data.</param>
    /// <param name="headerbar">The <see cref="IHeaderBar"/> on which to apply the feedback.</param>
    public delegate void HeaderBarStringInputSigDelegate(StringInputSig stringInputSig, IHeaderBar headerbar);

    /// <summary>
    /// HeaderBar
    /// </summary>
    internal partial class HeaderBar : IHeaderBar, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: HeaderBar.PowerButton.Press
                /// PowerButton.Press
                /// </summary>
                public const uint PowerButton_PressEvent = 3;


                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: HeaderBar.PowerButton.Selected
                /// PowerButton.Selected
                /// </summary>
                public const uint PowerButton_SelectedState = 3;

            }
            /// <summary>
            /// Serial signals.
            /// </summary>
            internal static class Strings
            {

                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: HeaderBar.RoomNameLabel.Indirect
                /// RoomNameLabel.Indirect
                /// </summary>
                public const uint RoomNameLabel_IndirectState = 1;
            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="HeaderBar"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal HeaderBar(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HeaderBar"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal HeaderBar(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="HeaderBar"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.PowerButton_PressEvent, onPowerButton_Press);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> PowerButton_PressEvent;
        private void onPowerButton_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = PowerButton_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public void PowerButton_Selected(HeaderBarBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.PowerButton_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void PowerButton_Selected(bool digital)
        {
            PowerButton_Selected((sig, component) => sig.BoolValue = digital);
        }


        /// <inheritdoc/>
        public void RoomNameLabel_Indirect(HeaderBarStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.RoomNameLabel_IndirectState], this);
            }
        }

        /// <inheritdoc/>
        public void RoomNameLabel_Indirect(string serial)
        {
            RoomNameLabel_Indirect((sig, component) => sig.StringValue = serial);
        }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "HeaderBar", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            PowerButton_PressEvent = null;
        }

        #endregion
    }
}
